apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/

namespace: ren-application-sit

patches:
- path: deployment.yaml
  target:
    version: v1
    kind: Deployment
    name: ren-application
- path: deployment-config-patch.yml
  target:
    version: v1
    kind: Deployment
    name: ren-application
- path: service.yaml
  target:
    kind: Service
    name: ren-application
    version: v1
- path: ingress.yaml
  target:
    kind: Ingress
    name: ren-ingress
    version: v1
- path: configmap.yaml
  target:
    kind: ConfigMap
    name: ren-application-config
    version: v1
- path: namespace.yaml
  target:
    kind: Namespace
    name: ren-application-sit
    version: v1
- patch: |-
    - op: replace
      path: /spec/data/0/remoteRef/key
      value: ren/zeebesit
    - op: replace
      path: /spec/data/1/remoteRef/key
      value: ren/zeebesit
  target:
    kind: ExternalSecret
    name: zeebe-secret
- patch: |-
    - op: replace
      path: /spec/data/0/remoteRef/key
      value: ren/rensit 
    - op: replace
      path: /spec/data/1/remoteRef/key
      value: ren/rensit 
  target:
    kind: ExternalSecret
    name: ren-secret
- path: secrets.yaml
  target:
    kind: ExternalSecret
    version: v1