resources:


- ../../base/

 

namespace: ren-application-sit

 

apiVersion: kustomize.config.k8s.io/v1beta1


kind: Kustomization

 

patches:


- path: deployment.yaml


  target:


    version: v1


    kind: Deployment


    name: ren-application


- path: service.yaml


  target:


    kind: Service


    name: ren-application


    version: v1


- path: ingress.yaml


  target:


    kind: Ingress


    name: ren-ingress


    version: v1


- patch: |-


    - op: replace


      path: /spec/data/0/remoteRef/key


      value: ren/zeebesit


    - op: replace


      path: /spec/data/1/remoteRef/key


      value: ren/zeebesit


  target:


    kind: ExternalSecret


    name: zeebe-secret


- patch: |-


    - op: replace


      path: /spec/data/0/remoteRef/key


      value: ren/rensit 


    - op: replace


      path: /spec/data/1/remoteRef/key


      value: ren/rensit 


  target:


    kind: ExternalSecret


    name: ren-secret