apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

 

resources:

- ../../base/

 

namespace: ren-application-gnp1

 

patches:

- path: deployment.yaml

  target:

    version: v1

    kind: Deployment

    name: ren-application

- path: deployment-config-patch.yaml

  target:

    version: v1

    kind: Deployment

    name: ren-application

- path: service.yaml

  target:

    kind: Service

    name: ren-application

    version: v1

- path: ingress.yaml

  target:

    kind: Ingress

    name: ren-ingress

    version: v1

- patch: |-

    - op: replace

      path: /spec/data/0/remoteRef/key

      value: ren/zeebegnp

    - op: replace

      path: /spec/data/1/remoteRef/key

      value: ren/zeebegnp

  target:

    kind: ExternalSecret

    name: zeebe-secret

- patch: |-

    - op: replace

      path: /spec/data/0/remoteRef/key

      value: ren/rengnp 

    - op: replace

      path: /spec/data/1/remoteRef/key

      value: ren/rengnp 

  target:

    kind: ExternalSecret

    name: ren-secret

 

# Using a ConfigMap generator to create a new ConfigMap for this overlay

configMapGenerator:

- name: ren-application-config

  behavior: replace

  files:

  - endpoints-config.yaml=endpoints-config.yaml

  - queries.yaml=queries.yaml 